# How to add a new service
# 1. Add the _IMAGE_NAME_SERVICENAME in substitutions
# 2. Copy the step 1 with the build and push steps with the dockerfile
# 3. Add the sed futher down and replace the image name in compose.yaml file with the _IMAGE_NAME_XXX you created in substitutions.

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE_NAME_BACKEND: "gcr.io/${PROJECT_ID}/backend/gcpdevops-prod:${SHORT_SHA}"
  _IMAGE_NAME_WEB: "gcr.io/${PROJECT_ID}/web/gcpdevops-prod:${SHORT_SHA}"
  _IMAGE_NAME_AUTH: "gcr.io/${PROJECT_ID}/auth/gcpdevops-prod:${SHORT_SHA}"
  _IMAGE_NAME_MIGRATE: "gcr.io/${PROJECT_ID}/migrate/gcpdevops-prod:${SHORT_SHA}"
  _CLUSTER_NAME: "meter-lab-production-standard-cluster"
  _NAMESPACE: "meter-lab"
  _LOCATION: "europe-north2"

steps:
  # Step 1: Build Docker images with SHA-based tagging
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'apps/backend/Dockerfile', '-t', '${_IMAGE_NAME_BACKEND}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'apps/web/Dockerfile', '-t', '${_IMAGE_NAME_WEB}', '--build-arg', 'PUBLIC_BACKEND_URL=https://api.nordicode.se', '--build-arg', 'PUBLIC_AUTH_URL=https://auth.nordicode.se', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'apps/auth/Dockerfile'
      - '-t'
      - '${_IMAGE_NAME_AUTH}'
      - '--build-arg'
      - 'PORT=5090'
      - '--build-arg'
      - 'DATABASE_HOST=auth-db'
      - '--build-arg'
      - 'DATABASE_PORT=5432'
      - '--build-arg'
      - 'DATABASE_USER=postgres'
      - '--build-arg'
      - 'DATABASE_PASSWORD=postgres'
      - '--build-arg'
      - 'DATABASE_NAME=auth'
      - '--build-arg'
      - 'BETTER_AUTH_SECRET=build-time-secret-replace-at-runtime'
      - '--build-arg'
      - 'BETTER_AUTH_URL=https://auth.nordicode.se'
      - '.'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'packages/migrate/Dockerfile', '-t', '${_IMAGE_NAME_MIGRATE}', '.']

  # Step 2: Push Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME_BACKEND}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME_WEB}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME_AUTH}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME_MIGRATE}']

  # 2) Install Kompose
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - |
        curl -L https://github.com/kubernetes/kompose/releases/download/v1.37.0/kompose-linux-amd64 -o kompose
        chmod +x kompose

  # 3) Convert docker-compose → manifest
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - |
        mkdir -p infra/gke/generated
        /workspace/kompose convert -f compose.yaml --stdout > infra/gke/generated/komposed.yaml

    # Step 3: Replace placeholder `image-name:latest` in `komposed.yaml` with actual image name 
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        # REPLACE IMAGE NAME IN KOMPOSE.YAML
        sed -i "s|backend:latest|${_IMAGE_NAME_BACKEND}|g" infra/gke/generated/komposed.yaml
        sed -i "s|web:latest|${_IMAGE_NAME_WEB}|g" infra/gke/generated/komposed.yaml
        sed -i "s|auth:latest|${_IMAGE_NAME_AUTH}|g" infra/gke/generated/komposed.yaml
        sed -i "s|migrate:latest|${_IMAGE_NAME_MIGRATE}|g" infra/gke/generated/komposed.yaml

        sed -i "s|port: 5090|port: 80|g" infra/gke/generated/komposed.yaml
        sed -i "s|port: 5080|port: 80|g" infra/gke/generated/komposed.yaml
        sed -i "s|port: 5070|port: 80|g" infra/gke/generated/komposed.yaml

        sed -i 's|value: development|value: stage|g' infra/gke/generated/komposed.yaml
        sed -i 's|value: prod|value: stage|g' infra/gke/generated/komposed.yaml
        sed -i '/hostPort/d' infra/gke/generated/komposed.yaml
        sed -i 's/imagePullPolicy: Never/imagePullPolicy: Always/g' infra/gke/generated/komposed.yaml
        sed -i 's|port: 5433|port: 5432|g' infra/gke/generated/komposed.yaml
        sed -i 's|name: "5433"|name: "5432"|g' infra/gke/generated/komposed.yaml
        awk '/port:/ && !/name:/ {gsub(/^[[:space:]]*- port:/, "  - name: port\n    port:"); print; next} {print}' infra/gke/generated/komposed.yaml > infra/gke/generated/komposed.tmp && mv infra/gke/generated/komposed.tmp infra/gke/generated/komposed.yaml

  # Cleanup previous gke-deploy outputs to avoid conflicts
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        rm -rf output || true

  # 5a) Deploy FAS 1: manual prereqs (namespace, secrets, configmaps, pvcs, crds, osv)
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --location=${_LOCATION}
      - --cluster=${_CLUSTER_NAME}
      - --namespace=${_NAMESPACE}
      - --filename=infra/k8s/gke

  # Apply kompose-generated resources and show diagnostics
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials ${_CLUSTER_NAME} --region ${_LOCATION}
        kubectl apply -f infra/gke/generated/ --namespace=${_NAMESPACE}
        sleep 10