options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE_NAME_BACKEND: "gcr.io/${PROJECT_ID}/backend/gcpdevops-prod:${SHORT_SHA}"
  _IMAGE_NAME_WEB: "gcr.io/${PROJECT_ID}/web/gcpdevops-prod:${SHORT_SHA}"
  _CLUSTER_NAME: "lnu-jti-production-standard-cluster"
  _NAMESPACE: "meter-lab"
  _LOCATION: "europe-north2"

steps:
  # Step 1: Build Docker images with SHA-based tagging
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'apps/backend/Dockerfile', '-t', '${_IMAGE_NAME_BACKEND}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'apps/web/Dockerfile', '-t', '${_IMAGE_NAME_WEB}', '.']

  # Step 2: Push Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME_BACKEND}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME_WEB}']

  # 2) Install Kompose
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - |
        curl -L https://github.com/kubernetes/kompose/releases/download/v1.37.0/kompose-linux-amd64 -o kompose
        chmod +x kompose

  # 3) Convert docker-compose → manifest
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - |
        mkdir -p gke/generated
        /workspace/kompose convert -f compose.yaml --stdout > gke/generated/komposed.yaml

    # Step 3: Replace placeholder `image-name:latest` in `komposed.yaml` with actual image name 
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        # REPLACE IMAGE NAME IN KOMPOSE.YAML
        sed -i "s|backend:latest|${_IMAGE_NAME_BACKEND}|g" gke/generated/komposed.yaml
        sed -i "s|web:latest|${_IMAGE_NAME_WEB}|g" gke/generated/komposed.yaml

        sed -i '/hostPort/d' gke/generated/komposed.yaml
        sed -i 's/imagePullPolicy: Never/imagePullPolicy: Always/g' gke/generated/komposed.yaml
        awk '/port:/ && !/name:/ {gsub(/^[[:space:]]*- port:/, "  - name: port\n    port:"); print; next} {print}' gke/generated/komposed.yaml > gke/generated/komposed.tmp && mv gke/generated/komposed.tmp gke/generated/komposed.yaml

  # Cleanup previous gke-deploy outputs to avoid conflicts
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        rm -rf output || true

  # 5a) Deploy FAS 1: manual prereqs (namespace, secrets, configmaps, pvcs, crds, osv)
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --location=${_LOCATION}
      - --cluster=${_CLUSTER_NAME}
      - --namespace=${_NAMESPACE}
      - --filename=k8s/gke

  # Apply kompose-generated resources and show diagnostics
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials ${_CLUSTER_NAME} --region ${_LOCATION}
        kubectl apply -f gke/generated/ --namespace=${_NAMESPACE}
        sleep 5