version: '3'

services:
  emqx:
    image: emqx/emqx-enterprise:6.0.1
    container_name: emqx1
    environment:
    - "EMQX_NODE_NAME=emqx@node1.emqx.com"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.com,emqx@node2.emqx.com]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    ports:
      - 1884:1883 # Use another port on the outside to prevent miss communication
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083 # Admin panel

  emqx-publisher:
    image: emqx-publisher:latest
    depends_on:
      - emqx
    build:
      context: .
      dockerfile: ./apps/emqx/Dockerfile
    environment:
      - BROKER_URL=${BROKER_URL:-mqtt://emqx:1883}
      - TOPIC=${TOPIC:-mock-data}
      - NUM_DEVICE=${NUM_DEVICE:-4}
    restart: unless-stopped